### ISSUE TITLE
Investigate crash.

### ISSUE THREAD

**Issue by artemii235** [JincorTech/backend-auth#36]
> auth@0.0.0 serve /usr/src/app
> node ./dist/bin/www.js

events.js:160
      throw er; // Unhandled 'error' event
      ^
ReplyError: Ready check failed: ERR max number of clients reached
    at parseError (/usr/src/app/node_modules/redis-parser/lib/parser.js:193:12)
    at parseType (/usr/src/app/node_modules/redis-parser/lib/parser.js:303:14)

npm ERR! Linux 4.9.36-x86_64-linode85
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "serve"
npm ERR! node v6.11.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! auth@0.0.0 serve: `node ./dist/bin/www.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the auth@0.0.0 serve script 'node ./dist/bin/www.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the auth package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./dist/bin/www.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs auth
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls auth
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/src/app/npm-debug.log

**Comment by hlogeon** [comment]
It seems like Reis is crashing. It supposed to be fixed by the last PR

**Comment by artemii235** [comment]
It was fixed, confirmed by load testing.
